spring:
  data:
    redis:
      host: 192.168.2.119
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8      # 连接池最大连接数
          min-idle: 2     # 最小空闲连接
server:
  port: 9000
# application.yml
#logging:
#  level:
#    root: DEBUG