spring:
  data:
    redis:
      host: 192.168.2.119
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8      # 连接池最大连接数
          min-idle: 2     # 最小空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.119:3306/test_db
    username: yangyang
    password: dsk16888..
    type: com.alibaba.druid.pool.DruidDataSource # 推荐 Druid 连接池
    druid:
      # 连接池大小配置
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 连接池中保持的最小空闲连接数
      max-active: 20 # 连接池中允许的最大活动连接数
      max-wait: 60000

      # 连接检测配置
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 # 用来检测连接是否有效的sql
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # 缓存配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

      # 过滤器配置（用于统计和监控）
      filters: stat,wall,log4j
# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.yy.redis.domain  # 替换为你的实体类包名
  mapper-locations: classpath:mapper/*.xml # 指定Mapper XML文件路径
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL日志到控制台
server:
  port: 9000
# application.yml
#logging:
#  level:
#    root: DEBUG